---
name: CI

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57 # v8.0.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache prek
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae  # v5.0.5
        with:
          path: ~/.cache/prek
          key: prek-|${{ matrix.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Lint
        run: |
          uv run prek run --all-files
      - name: Lint GitHub Actions
        uses: eifinger/actionlint-action@v1
